### ISSUE TITLE
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.23' not found

### ISSUE THREAD

**Issue by scrossan-crown** [parcel-bundler/watcher#18] opened 2019-08-16 12:05 UTC
I'm getting this error when trying to run `npx parcel -p 1234 --hmr-port 1235 index.html` with `2.0.0-alpaha.1.1`

```
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.23' not found (required by /app/node_modules/@parcel/core/node_modules/@parcel/watcher/build/Release/watcher.node) 
```

**Comment by embeddedt** [comment] 2019-08-16 12:12
I had the same issue (with Parcel 2).

I was able to work around this problem by installing a newer version of the standard C library from the [`ubuntu-toolchain-r/test`](https://wiki.ubuntu.com/ToolChain#PPA_packages) PPA. After doing that, Parcel was able to run without errors. However, I don't think this extra step should be necessary.

My guess as to why the issue is happening is that the Parcel v2 installation process does not rebuild the native components, which are presumably linked against a newer standard C library.

**Comment by scrossan-crown** [comment] 2019-08-16 12:13
I'm using debian but I'm guessing there is a similar solution

**Comment by mischnic** [comment] 2019-08-16 15:19
>  which are presumably linked against a newer standard C library.

which version did you have installed previously (both ubuntu/debian & libc)?  Maybe we can require a lower libc when building the prebuilt binaries.

**Comment by embeddedt** [comment] 2019-08-16 15:38
> which version did you have installed previously (both ubuntu/debian & libc)?

Ubuntu 16.04. I'm not sure what libc version it comes with.

> Maybe we can require a lower libc when building the prebuilt binaries.

A better option, IMO, is to do what `node-sass` and other native projects do: test the prebuilt binary,  and if it fails to work for any reason, just compile a new one on the machine. Is that possible?

**Comment by devongovett** [comment] 2019-08-16 16:24
Hmm, we are building against 16.04 in CI... https://github.com/parcel-bundler/watcher/blob/master/azure-pipelines.yml#L18

**Comment by embeddedt** [comment] 2019-08-16 17:24
Interesting. I run updates very frequently on this machine so it shouldn't be using an outdated libc.

I'll remove the PPA so I can investigate further.

**Comment by d3x7r0** [comment] 2019-08-20 10:35
I was just trying it out and got the same issue running on CentOS 7.

**Comment by mdchristians** [comment] 2019-11-10 20:26
Running into this too when trying to build using Netlify.

<img width="983" alt="Screen Shot 2019-11-10 at 2 25 11 PM" src="https://user-images.githubusercontent.com/4482233/68550153-fc075100-03c5-11ea-9e0f-d6bdd933598a.png">

**Comment by midnightcodr** [comment] 2019-12-13 14:18
Running into the same issue with Centos 7.6.1810 and "parcel": "^2.0.0-alpha.3.2".

**Comment by wojtekmaj** [comment] 2019-12-17 12:45
Running into the same issue on Travis CI.

**Comment by pke** [comment] 2020-01-07 23:57
Can't it just use the same dependency as parcel@1? I am running into issues on zeit.now too. Filed a support request there to upgrade the lib (I guess they are just at .22 there, just like I was locally).

Any reasons for the new libc requirements?

**Comment by verikono** [comment] 2020-01-09 19:08
Ubuntu 16.04/Xenial is having this issue too.

**Comment by jessehattabaugh** [comment] 2020-01-10 23:23
I get this error when I build on Netlify, even though I'm just running `parcel build src/index.html` which shouldn't need to start a watcher.

**Comment by mischnic** [comment] 2020-01-11 10:51
@jessehattabaugh This module can also create a snapshot of a directory, so that on the next invocation of parcel, only the changed files are rebuilt.

**Comment by jessehattabaugh** [comment] 2020-01-11 13:50
@mischnic I see, but in many cases the environment where parcel runs gets entirely thrown away after the first invocation. Seems like uneccessary work in that situation.

**Comment by DeMoorJasper** [comment] 2020-01-11 14:38
@jessehattabaugh we can't really detect whether the a CI/CD server does any persisting so we just always do it, also the --no-cache just doesn't reuse cache it still uses the cache as we use it to share files between processes and some other things as it improves performance.

**Comment by jessehattabaugh** [comment] 2020-01-11 19:56
@DeMoorJasper Understood. I guess I'm out of workaround ideas then... Any chance you can test for the existence of this lib and build it if it doesn't as @embeddedt suggested?

**Comment by DeMoorJasper** [comment] 2020-01-11 19:59
That's what we currently do, however we need to build against a lower libc so this error no longer occurs like the PR implements

**Comment by jessehattabaugh** [comment] 2020-01-11 20:02
Didn't see the PR! My bad.

**Comment by devongovett** [comment] 2020-02-09 18:35
This should be fixed now that #24 is merged. It's released in @parcel/watcher v2.0.0-alpha.5.

**Closed by devongovett** 2020-02-09 18:35 UTC

**Comment by sw-yx** [comment] 2020-03-03 00:26
@devongovett mind updating @parcel/fs? seems you still have its watcher version pinned to alpha.4 https://github.com/parcel-bundler/parcel/blob/v2/packages/core/fs/package.json#L20

**Comment by sw-yx** [comment] 2020-03-03 00:27
there doesn't seem to be a @nightly tag for @parcel/watcher either idk if that caused it
